#!/usr/bin/env bash
#
# Provision a fresh Hetzner (or any Debian 12/13) server to run deskswarm.
#
# Run it on the new box as root:
#
#   ssh root@<ip> 'bash -s' < deploy/hetzner-setup.sh
#
# or with a domain, which is what turns HTTPS on:
#
#   ssh root@<ip> DESKSWARM_DOMAIN=swarm.example.com 'bash -s' < deploy/hetzner-setup.sh
#
# What it does, in order: firewall, Docker, the repo, secrets, TLS, start.
# Everything is idempotent — running it twice changes nothing the second time.
#
# ---------------------------------------------------------------------------
# READ THIS BEFORE PUTTING IT ON A PUBLIC ADDRESS
#
# The dashboard mounts /var/run/docker.sock. That is root on this host. The
# login in front of it is real, but it is one password between the internet and
# a root shell, so this script does NOT publish the dashboard directly:
#
#   * the dashboard binds to 127.0.0.1 only
#   * Caddy terminates TLS in front of it and is the only thing on 80/443
#   * the firewall allows 22, 80 and 443, and nothing else
#
# The machines' screens are the awkward part. A tile links to the machine's own
# noVNC on 6901+, and on a public box that means opening a port range whose
# only protection is each machine's random VNC password. This script leaves
# those ports CLOSED. Two ways to see a screen with them closed:
#
#   * the wall works — it polls stills through the dashboard, which is
#     authenticated, and so do share links
#   * for full keyboard and mouse, tunnel: ssh -L 6901:127.0.0.1:6901 root@<ip>
#
# Set OPEN_SCREEN_PORTS=yes to open 6901-6950 anyway. It is a real trade and
# the script will not make it for you.
# ---------------------------------------------------------------------------

set -euo pipefail

DOMAIN="${DESKSWARM_DOMAIN:-}"
OPEN_SCREEN_PORTS="${OPEN_SCREEN_PORTS:-no}"
REPO="${DESKSWARM_REPO:-https://github.com/ahmedvnabil/deskswarm.git}"
DIR="/opt/deskswarm"
SCREEN_PORTS="6901:6950"

log() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

[ "$(id -u)" -eq 0 ] || { echo "run this as root"; exit 1; }

# ------------------------------------------------------------------ system

log "packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl git ufw fail2ban >/dev/null

log "firewall"
ufw --force reset >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow 22/tcp    comment 'ssh'      >/dev/null
ufw allow 80/tcp    comment 'http'     >/dev/null
ufw allow 443/tcp   comment 'https'    >/dev/null
if [ "$OPEN_SCREEN_PORTS" = "yes" ]; then
  ufw allow "${SCREEN_PORTS}/tcp" comment 'novnc screens' >/dev/null
  echo "    screen ports ${SCREEN_PORTS} are OPEN — each machine's random VNC"
  echo "    password is the only thing in front of them"
fi
ufw --force enable >/dev/null
ufw status numbered | sed 's/^/    /'

log "ssh: keys only"
# The key you already used to get here keeps working; this only closes the
# password door, which is what the bots on a public IP are knocking on.
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
systemctl reload ssh 2>/dev/null || systemctl reload sshd
systemctl enable --now fail2ban >/dev/null 2>&1 || true

# ------------------------------------------------------------------ docker

if ! command -v docker >/dev/null 2>&1; then
  log "docker"
  curl -fsSL https://get.docker.com | sh >/dev/null
  systemctl enable --now docker >/dev/null
fi
docker --version | sed 's/^/    /'

# -------------------------------------------------------------------- app

log "deskswarm"
if [ -d "$DIR/.git" ]; then
  git -C "$DIR" pull --ff-only
else
  git clone --depth 1 "$REPO" "$DIR"
fi

# Secrets are generated once and never regenerated, so re-running this does not
# lock you out of the dashboard you are already signed in to.
if [ ! -f "$DIR/.env" ]; then
  log "secrets"
  ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
  API_TOKEN="$(openssl rand -hex 24)"
  cat > "$DIR/.env" <<EOF
# Generated by deploy/hetzner-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# The dashboard listens on loopback only; Caddy is what the internet reaches.
DASHBOARD_PORT=127.0.0.1:7861

DESKSWARM_ADMIN_USER=admin
DESKSWARM_ADMIN_PASSWORD=${ADMIN_PASSWORD}
DASHBOARD_TOKEN=${API_TOKEN}

# Screen links have to name the address the *browser* uses.
DESKSWARM_PUBLIC_HOST=${DOMAIN}

# Measured: a machine is ~400 MB idle and past 600 MB with a browser open.
# Leave the guard a real number rather than letting it read the host's.
DESKSWARM_MEMORY_BUDGET_MB=$(( $(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo) - 1024 ))

# Uncomment and fill in to let agents run. Everything else works without it.
# DESKSWARM_MODEL=anthropic/claude-sonnet-5
# DESKSWARM_API_KEY=
EOF
  chmod 600 "$DIR/.env"
  echo "    written to $DIR/.env (0600)"
else
  echo "    .env already exists — left alone"
fi

# -------------------------------------------------------------------- tls

if [ -n "$DOMAIN" ]; then
  log "caddy — automatic HTTPS for $DOMAIN"
  install -d /etc/caddy
  cat > /etc/caddy/Caddyfile <<EOF
${DOMAIN} {
    encode zstd gzip
    # The dashboard is on loopback; this is the only way in from outside.
    reverse_proxy 127.0.0.1:7861
}
EOF
  if ! docker ps --format '{{.Names}}' | grep -q '^deskswarm-caddy$'; then
    docker rm -f deskswarm-caddy >/dev/null 2>&1 || true
    docker run -d --name deskswarm-caddy --restart unless-stopped \
      --network host \
      -v /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro \
      -v caddy_data:/data -v caddy_config:/config \
      caddy:2 >/dev/null
  else
    docker exec deskswarm-caddy caddy reload --config /etc/caddy/Caddyfile >/dev/null
  fi
  echo "    point ${DOMAIN} at this server's A record; the certificate is automatic"
else
  echo
  echo "    no DESKSWARM_DOMAIN set, so there is no TLS and nothing is published."
  echo "    Reach it over SSH until you have a name for it:"
  echo "      ssh -L 7861:127.0.0.1:7861 root@<this server>"
  echo "    then open http://127.0.0.1:7861"
fi

# ------------------------------------------------------------------- start

log "starting"
cd "$DIR"
docker compose up -d --build

for _ in $(seq 1 60); do
  sleep 2
  if curl -fsS -o /dev/null --max-time 3 http://127.0.0.1:7861/health 2>/dev/null; then
    break
  fi
done

log "done"
docker compose ps --format '    {{.Name}}  {{.Status}}'
echo
if [ -f "$DIR/.env" ]; then
  echo "    sign in as:  $(grep '^DESKSWARM_ADMIN_USER=' "$DIR/.env" | cut -d= -f2)"
  echo "    password:    $(grep '^DESKSWARM_ADMIN_PASSWORD=' "$DIR/.env" | cut -d= -f2)"
  echo "    api token:   $(grep '^DASHBOARD_TOKEN=' "$DIR/.env" | cut -d= -f2)"
  echo
  echo "    Change the password after the first sign-in:"
  echo "      cd $DIR && docker compose exec dashboard bun run src/cli.ts passwd admin"
fi
[ -n "$DOMAIN" ] && echo "    https://${DOMAIN}"
echo
